framework:
    messenger:
        failure_transport: failed
        default_bus: command_bus
        buses:
            command_bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
                middleware:
                    - validation
                    - doctrine_transaction
                    #- router_context
            query_bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
                middleware:
                    - validation
                    - doctrine_transaction
                    #- router_context
            event_bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                middleware:
                    - validation
                    - doctrine_transaction
                    #- router_context
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: failed
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 1
                    jitter: 0.1
            failed: '%env(MESSENGER_TRANSPORT_DSN_FAILED)%'
            sync: 'sync://'
        routing:
            # 'Symfony\Component\Mailer\Messenger\SendEmailMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
