when@dev:
    nelmio_api_doc:
        documentation:
            info:
                title: Task Manager REST API
                description: REST API
                version: 0.0.1
            components:
                securitySchemes:
                    Bearer:
                        type: http
                        scheme: bearer
                        bearerFormat: JWT
            security:
                - Bearer: []
        areas:
            default:
                path_patterns:
                    - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            #other_api:
                #path_patterns: [ ^/other-api/ ]
