doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Domain/Entity'
                        prefix: 'App\Domain\Entity'
                        alias: App
